// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Dec 14 14:28:54 2009

#include "TemplatePluginSandboxPanelWidgetUI.h"

// begin wxGlade: ::extracode

// end wxGlade


TemplatePluginSandboxPanelWidgetUI::TemplatePluginSandboxPanelWidgetUI(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: TemplatePluginSandboxPanelWidgetUI::TemplatePluginSandboxPanelWidgetUI
    m_btnApply = new wxButton(this, wxID_BTN_Apply, wxT("Apply"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(TemplatePluginSandboxPanelWidgetUI, wxScrolledWindow)
    // begin wxGlade: TemplatePluginSandboxPanelWidgetUI::event_table
    EVT_BUTTON(wxID_BTN_Apply, TemplatePluginSandboxPanelWidgetUI::OnBtnApply)
    // end wxGlade
END_EVENT_TABLE();


void TemplatePluginSandboxPanelWidgetUI::OnBtnApply(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TemplatePluginSandboxPanelWidgetUI::OnBtnApply) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add TemplatePluginSandboxPanelWidgetUI event handlers


void TemplatePluginSandboxPanelWidgetUI::set_properties()
{
    // begin wxGlade: TemplatePluginSandboxPanelWidgetUI::set_properties
    SetScrollRate(10, 10);
    // end wxGlade
}


void TemplatePluginSandboxPanelWidgetUI::do_layout()
{
    // begin wxGlade: TemplatePluginSandboxPanelWidgetUI::do_layout
    wxBoxSizer* GlobalSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_btnApply, 0, wxALL|wxEXPAND, 5);
    GlobalSizer->Add(sizer_1, 0, wxEXPAND, 5);
    SetSizer(GlobalSizer);
    GlobalSizer->Fit(this);
    // end wxGlade
}

